### ISSUE TITLE
Stable v2 release date

### ISSUE THREAD

**Issue by IS-Vivek** [aws/serverless-java-container#674]
*To help us debug your issue fill in the basic information below using the options provided*

*Serverless Java Container version*: 1.8.1

*Implementations:* Spring Boot 

*Framework version:* Spring Boot 2.7,13

*Frontend service:* ALB

*Deployment method:* Serverless Framework

## Scenario
*Describe what you are trying to accomplish*
We are waiting trying to update our spring boot version to 3. However, we are waiting to see a stable release of the "aws-serverless-java-container" to do this. Is there any planned timeframe or release date for the next major version (v2) of the "aws-serverless-java-container" to support this.

**Comment by deki** [comment]
Hi @IS-Vivek, 
thanks for reaching out. Our M1 and M2 releases are ready to be used in production but there will be an additional breaking change on API-level that's why we haven't released 2.0.0 yet. We will move to the AWS Lambda Java Events library https://github.com/aws/aws-lambda-java-libs/tree/master/aws-lambda-java-events/ and are waiting for their 4.0.0 release. I will update this issue once we have a release plan.

Feel free to reach out to your AWS account team (or via https://aws.amazon.com/contact-us/sales-support/) to discuss in more detail.

**Comment by nedelva** [comment]
@deki, it's been almost **two years** since this major change to [Java Events V4 was announced,](https://github.com/aws/aws-lambda-java-libs/issues/282) and yet no release date is in sight. Wouldn't you guys be better off you stick with Lambda Java Events V3 for the time being?

**Comment by deki** [comment]
@nedelva you are absolutely right and we are actively looking into that option right now.

**Comment by eximius313** [comment]
@deki, have you decided anything?

**Comment by deki** [comment]
Happy new year! We are working on the release, my plan is to get in done by end of this month.

**Comment by eximius313** [comment]
awesome, thanks!

**Comment by deki** [comment]
Quick update: We plan for the 2.0.0 release to be available next week.

**Comment by deki** [comment]
The release is now available on Maven Central. Thank you for your patience.
